In [1]:
cd

C:\Users\lenovo1

In [2]:
import pandas as pd
import numpy as np

In [3]:
mov = pd.read_csv("movies.csv")

In [4]:
mov.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [5]:
link = pd.read_csv("links.csv")
rat = pd.read_csv("ratings.csv")
tag  = pd.read_csv("tags.csv")

In [6]:
lin.head()

NameError: name 'lin' is not defined

In [7]:
link.head()

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [8]:
rat.head()

   userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [9]:
tag.head

<bound method NDFrame.head of       userId  movieId                                                tag  \
0         15      339                            sandra 'boring' bullock
1         15     1955                                            dentist
2         15     7478                                           Cambodia
3         15    32892                                            Russian
4         15    34162                                        forgettable
5         15    35957                                              short
6         15    37729                                         dull story
7         15    45950                                         powerpoint
8         15   100365                                           activist
9         15   100365                                        documentary
10        15   100365                                             uganda
11        23      150                                         Ron Howard
12        68     2174                                              music
13        68     2174                                              weird
14        68     8623                                       Steve Martin
15        73   107999                                             action
16        73   107999                                              anime
17        73   107999                                            kung fu
18        73   111624                                              drama
19        73   111624                                              indie
20        73   111624                                               love
21        73   130682                                            b movie
22        73   130682                                             comedt
23        73   130682                                             horror
24        77     1199                         Trilogy of the Imagination
25        77     2968                                            Gilliam
26        77     2968                         Trilogy of the Imagination
27        77     4467                         Trilogy of the Imagination
28        77     4911                                            Gilliam
29        77     5909                                      Takashi Miike
...      ...      ...                                                ...
1266     547   163949                                          toplist16
1267     547   164977                                               tivo
1268     547   164979                                               tivo
1269     567   138610                                      found footage
1270     567   138610                                    survival horror
1271     574    47044                                       Michael Mann
1272     583   112552                                      determination
1273     583   112552                                           devotion
1274     583   112552                                              music
1275     599    66203                                             honest
1276     599    82152                                      alex pettyfer
1277     611   105504                                          hijacking
1278     611   105504                                              ocean
1279     611   105504                                            pirates
1280     611   105504                                           suspense
1281     615   111384                                            revenge
1282     615   111384                                          vengeance
1283     615   111931                                       femme-fatale
1284     615   111931                                             gritty
1285     615   111931                                         low-budget
1286     630      260                                     classic sci-fi
1287     630      260                                             series
1288     652   146501                                                gay
1289     660      260  imaginary world, characters, story, philosophical
1290     660      260                                             script
1291     660   135518                                    meaning of life
1292     660   135518                                      philosophical
1293     660   135518                                             sci-fi
1294     663      260                                             action
1295     663      260                                               Syfy

       timestamp
0     1138537770
1     1193435061
2     1170560997
3     1170626366
4     1141391765
5     1141391873
6     1141391806
7     1169616291
8     1425876220
9     1425876220
10    1425876220
11    1148672905
12    1249808064
13    1249808102
14    1249808497
15    1430799184
16    1430799184
17    1430799184
18    1431584497
19    1431584497
20    1431584497
21    1432523704
22    1432523704
23    1432523704
24    1163220043
25    1163220138
26    1163220039
27    1163220065
28    1163220167
29    1163219591
...          ...
1266  1476419254
1267  1476113746
1268  1476113908
1269  1436827601
1270  1436827612
1271  1232812787
1272  1430526450
1273  1430526450
1274  1430526450
1275  1344134759
1276  1306109318
1277  1471521058
1278  1471521036
1279  1471521067
1280  1471521044
1281  1408781036
1282  1408781025
1283  1425503802
1284  1425503802
1285  1425503802
1286  1443807766
1287  1443807803
1288  1449533216
1289  1436680217
1290  1436680177
1291  1436680885
1292  1436680885
1293  1436680885
1294  1438398078
1295  1438398050

[1296 rows x 4 columns]>

In [10]:
tag.head()

   userId  movieId                      tag   timestamp
0      15      339  sandra 'boring' bullock  1138537770
1      15     1955                  dentist  1193435061
2      15     7478                 Cambodia  1170560997
3      15    32892                  Russian  1170626366
4      15    34162              forgettable  1141391765

In [11]:
# Merging movies and links first

In [12]:
merged = mov.merge(link, on='movieId')

In [13]:
merged.head()

,movieId,title,genres,imdbId,tmdbId
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0
1,2,Jumanji (1995),Adventure|Children|Fantasy,113497,8844.0
2,3,Grumpier Old Men (1995),Comedy|Romance,113228,15602.0
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,114885,31357.0
4,5,Father of the Bride Part II (1995),Comedy,113041,11862.0

In [14]:
# Merging rating now

In [15]:
merged2 = merged.merge(rat, on='movieId')

In [16]:
merged2.head()

,movieId,title,genres,imdbId,tmdbId,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,7,3.0,851866703
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,9,4.0,938629179
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,13,5.0,1331380058
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,15,2.0,997938310
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,19,3.0,855190091

In [17]:
# Merging tags now

In [18]:
mergedfinal = merged2.merge(tag, on='movieId')

In [19]:
mergedfinal.head()

,movieId,title,genres,imdbId,tmdbId,userId_x,rating,timestamp_x,userId_y,tag,timestamp_y
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,7,3.0,851866703,501,Pixar,1292956344
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,9,4.0,938629179,501,Pixar,1292956344
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,13,5.0,1331380058,501,Pixar,1292956344
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,15,2.0,997938310,501,Pixar,1292956344
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,19,3.0,855190091,501,Pixar,1292956344

In [20]:
mergedfinal

,movieId,title,genres,imdbId,tmdbId,userId_x,rating,timestamp_x,userId_y,tag,timestamp_y
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,7,3.0,851866703,501,Pixar,1292956344
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,9,4.0,938629179,501,Pixar,1292956344
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,13,5.0,1331380058,501,Pixar,1292956344
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,15,2.0,997938310,501,Pixar,1292956344
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,19,3.0,855190091,501,Pixar,1292956344
5,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,20,3.5,1238729767,501,Pixar,1292956344
6,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,23,3.0,1148729853,501,Pixar,1292956344
7,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,26,5.0,1360087980,501,Pixar,1292956344
8,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,30,4.0,944943070,501,Pixar,1292956344
9,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,37,4.0,981308121,501,Pixar,1292956344
10,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,43,4.0,974768260,501,Pixar,1292956344
11,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,44,4.0,858707138,501,Pixar,1292956344
12,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,47,5.0,832228931,501,Pixar,1292956344
13,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,48,4.0,1318796720,501,Pixar,1292956344
14,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,55,3.0,855926941,501,Pixar,1292956344
15,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,56,4.0,1467004817,501,Pixar,1292956344
16,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,63,5.0,1079098216,501,Pixar,1292956344
17,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,67,3.0,854711770,501,Pixar,1292956344
18,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,68,4.0,1194741818,501,Pixar,1292956344
19,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,69,5.0,1366831110,501,Pixar,1292956344
20,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,70,5.0,853954235,501,Pixar,1292956344
21,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,72,3.5,1461778737,501,Pixar,1292956344
22,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,73,5.0,1303464840,501,Pixar,1292956344
23,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,75,3.0,1165607201,501,Pixar,1292956344
24,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,77,4.0,1163005363,501,Pixar,1292956344
25,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,79,2.0,1182994648,501,Pixar,1292956344
26,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,84,3.5,1429910800,501,Pixar,1292956344
27,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,86,3.0,848161799,501,Pixar,1292956344
28,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,87,3.0,858623186,501,Pixar,1292956344
29,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,862.0,89,5.0,1257620018,501,Pixar,1292956344
...,...,...,...,...,...,...,...,...,...,...,...
63095,142488,Spotlight (2015),Thriller,1895587,314365.0,56,4.0,1467004133,547,toplist15,1449754627
63096,142488,Spotlight (2015),Thriller,1895587,314365.0,72,3.0,1461778632,547,toplist15,1449754627
63097,142488,Spotlight (2015),Thriller,1895587,314365.0,270,4.5,1469256805,547,toplist15,1449754627
63098,142488,Spotlight (2015),Thriller,1895587,314365.0,457,2.0,1471386260,547,toplist15,1449754627
63099,142488,Spotlight (2015),Thriller,1895587,314365.0,475,5.0,1454428201,547,toplist15,1449754627
63100,142488,Spotlight (2015),Thriller,1895587,314365.0,547,4.0,1452944320,547,toplist15,1449754627
63101,142488,Spotlight (2015),Thriller,1895587,314365.0,570,4.0,1475806253,547,toplist15,1449754627
63102,142488,Spotlight (2015),Thriller,1895587,314365.0,648,4.5,1457736015,547,toplist15,1449754627
63103,143385,Bridge of Spies (2015),Drama|Thriller,3682448,296098.0,15,2.5,1458506017,547,toplist15,1446211337
63104,143385,Bridge of Spies (2015),Drama|Thriller,3682448,296098.0,371,4.5,1462745370,547,toplist15,1446211337
63105,143385,Bridge of Spies (2015),Drama|Thriller,3682448,296098.0,547,3.5,1446812004,547,toplist15,1446211337
63106,146501,Land of Storms (2014),Drama,2474310,254005.0,652,2.5,1449533204,652,gay,1449533216
63107,146656,Creed (2015),Drama,3076658,312221.0,15,3.5,1458506016,547,toplist15,1449755899
63108,146656,Creed (2015),Drama,3076658,312221.0,56,5.0,1467005847,547,toplist15,1449755899
63109,146656,Creed (2015),Drama,3076658,312221.0,62,4.0,1465279438,547,toplist15,1449755899
63110,146656,Creed (2015),Drama,3076658,312221.0,73,4.0,1456038516,547,toplist15,1449755899
63111,146656,Creed (2015),Drama,3076658,312221.0,475,4.5,1454428219,547,toplist15,1449755899
63112,146656,Creed (2015),Drama,3076658,312221.0,547,4.0,1458652849,547,toplist15,1449755899
63113,148626,"Big Short, The (2015)",Drama,1596363,318846.0,15,3.5,1458505924,547,toplist15,1449755637
63114,148626,"Big Short, The (2015)",Drama,1596363,318846.0,56,2.0,1470350805,547,toplist15,1449755637
63115,148626,"Big Short, The (2015)",Drama,1596363,318846.0,73,3.5,1457332236,547,toplist15,1449755637
63116,148626,"Big Short, The (2015)",Drama,1596363,318846.0,238,3.0,1459365379,547,toplist15,1449755637
63117,148626,"Big Short, The (2015)",Drama,1596363,318846.0,277,3.5,1463682406,547,toplist15,1449755637
63118,148626,"Big Short, The (2015)",Drama,1596363,318846.0,371,4.0,1462747151,547,toplist15,1449755637
63119,148626,"Big Short, The (2015)",Drama,1596363,318846.0,475,5.0,1454428198,547,toplist15,1449755637
63120,148626,"Big Short, The (2015)",Drama,1596363,318846.0,547,4.5,1454163886,547,toplist15,1449755637
63121,148626,"Big Short, The (2015)",Drama,1596363,318846.0,570,4.0,1475806416,547,toplist15,1449755637
63122,148626,"Big Short, The (2015)",Drama,1596363,318846.0,655,3.0,1470075763,547,toplist15,1449755637
63123,156387,Sing Street (2016),Drama,3544112,369557.0,547,4.0,1467946613,547,toplist16,1467946629
63124,163949,The Beatles: Eight Days a Week - The Touring Y...,Documentary,2531318,391698.0,547,5.0,1476419239,547,toplist16,1476419254

In [21]:
# Merged all csv files i.e. Movies. Links, Ratings, and Tags

In [22]:
# Don't understand the "userId_x" and userId_y" attributes